### ISSUE TITLE
404 occured

### ISSUE THREAD

**Issue by Mattony** [fbg13/WireManga#2]
Hi it's been a few days since this error is appearing in the console when someone reads the manga.
404 occurred: /site/templates/assets/js/jquery.preload.min.js

and in the reader when I go forward with the pages it appears to me #reader-header. 
For examples: manga/vanitas-no-carte/20/2/#reader-header

**Comment by fbg13** [comment]
The 404  occurs because the name of the js file is wrong in the code. I have [removed the code](https://github.com/fbg13/WireMangaTheme/commit/46626b1c179c85a549fbaa1ea2b032dfa7893634) altogether it doesn't seem to worked to well.

You can replace the content of your `/site/templates/wm_chapter.php` file with https://github.com/fbg13/WireMangaTheme/blob/master/TemplateFiles/wm_chapter.php

Or you can change 
`$footerAssets .= "<script src='{$config->urls->templates}assets/js/jquery.preload.min.js' async=''></script>\n";`
to
`$footerAssets .= "<script src='{$config->urls->templates}assets/js/preloadjs.min.js' async=''></script>\n";`
to load the correct script.

As for the #reader-header in the url that makes the page scroll down to the element with the id #reader-header.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#Linking_to_another_section_on_the_same_page

**Comment by Mattony** [comment]
okay I replaced the whole content, but the error continues to appear!
now I try to change only the script and see if it works!

As for the #reader-header so it's normal that it appears?

**Comment by fbg13** [comment]
> okay I replaced the whole content, but the error continues to appear!
Maybe it was a cache issue.

>As for the #reader-header so it's normal that it appears?
Yes

**Comment by Mattony** [comment]
no because I even deleted it!
Anyway...  Now I would have some advice to ask you. I'm a beginner so many things I can not do and that's why I ask.

- In theme setting when changing the menu, what is the purpose of the class?
- I would like to center the content of the site and not expand it to full screen. How can I use the container function?
- how can I change the layout of Latest Chapters, Latest Manga and Popular Manga

**Comment by fbg13** [comment]
> In theme setting when changing the menu, what is the purpose of the class?

It adds a class to the list tag `<li class="your-class-name">...</li>`

>I would like to center the content of the site and not expand it to full screen. 

There's a "Limit Page Width" option in the settings which limits the page width to 1200px, you'll have to write your own css for more control.

>How can I use the container function?

Don't know what container function you mean.

>how can I change the layout of Latest Chapters, Latest Manga and Popular Manga

You'll have to edit the code for that. 

The files responsible for the home page are `templates/home.php` and `templates/views/Home.php`. The `templates/home.php` gets variables needed for that page/template and passes them to `templates/views/Home.php`, where they are inserted in the html.

Best way to change the default look/behavior is to create an `_overrides` folder inside the `templates` folder and copy the file of the template you want to edit (home.php in this case) inside it, you also need a views folder with the corresponding file for the template you change (Home.php) and edit those.

`templates/_overrides/views/Home.php`
`templates/_overrides/home.php`

**Comment by Mattony** [comment]
okay perfect, thanks for the reply! I'll try to fix it
anyway...
- how can I add a users creator?
- Is it possible to insert a menu with the dropdown?
- how much bandwidth does the script use? Because it consumed 8.5gb in a day without even having advertised it!

**Comment by fbg13** [comment]
> how can I add a users creator?

Don't know what you mean.

>Is it possible to insert a menu with the dropdown?

Yes
![peek 2018-01-17 16-21](https://user-images.githubusercontent.com/6839895/35047442-9941eb16-fba2-11e7-9739-3c98adf7df21.gif)

>how much bandwidth does the script use? Because it consumed 8.5gb in a day without even having advertised it!

It doesn't have a default bandwidth usage, those gb are probably from uploading.
